name: Conventional Commits

on:
  pull_request:
    branches: [main]
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validation Naming Conventions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Please look up the latest version from
      # https://github.com/roseline124/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (newline-delimited).
          # Default: https://github.com/commitizen/conventional-commit-types
          types: |
            fix
            feat
            chore

      - uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional, set if you want a subset of commit types to be allowed.
          allowed-commit-types: "feat,fix,chore"
