name: Validate Naming Standards

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate Naming Standards
    runs-on: ubuntu-latest
    steps:
      - name: Validate Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore

      - name: Validate Commits
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          allowed-commit-types: "feat,fix,chore"
