name: Validate Naming Standards

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main

jobs:
  main:
    name: Validate Naming Standards
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4

      - name: Validate Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (newline-delimited).
          # Default: https://github.com/commitizen/conventional-commit-types
          types: |
            fix
            feat
            chore

      - name: Validate Commits
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional, set if you want a subset of commit types to be allowed.
          allowed-commit-types: "feat,fix,chore"
